TeamHavit/Havit-Server

functions/.gitignore, functions/constants/jwt.js, functions/lib/jwtHandlers.js, functions/middlewares/auth.js, functions/package-lock.json, functions/package.json
* jwt 라이브러리 추가
* jwtHandlers 추가 
* jwt header 검증 코드 추가 
일단 세미나 자료에서 가져온거라 우리가 실제로 구현할때 자잘하게 손봐야 할 부분은 있을듯
=> [FEAT] jwt token 핸들러, 발급 코드 추가

functions/api/routes/content/checkPATCH.js, functions/api/routes/content/index.js, functions/constants/responseMessage.js, functions/db/content.js, functions/index.js
- 콘텐츠 조회 여부 토글 responseMessage 추가
- Firebase key 파싱 방법 수정
- 콘텐츠 조회 여부 토글 api 구현
=> [FEAT] POST /content/check 콘텐츠 조회 여부 토글 api

functions/db/content.js, functions/db/user.js
- 콘텐츠 알림 시각 변경 API 알림 Off->On 변경 시 로직 수정
=> [FIX] 콘텐츠 알림 시각 변경 API 알림 Off->On 변경 시 로직 수정

functions/api/routes/content/contentListGET.js, functions/db/content.js, functions/db/user.js
- 콘텐츠 전체 조회 API filter, option 추가
=> [FEAT] 콘텐츠 전체 조회 API filter, option 추가

functions/api/routes/user/index.js, functions/api/routes/user/userUpdateFcmTokenPUT.js, functions/constants/responseMessage.js, functions/package-lock.json
=> [FEAT] FCM token refresh API 연결

functions/db/user.js
[[CHORE] 닉네임 업데이트 쿼리문 edited_at 추가
=> [CHORE] 닉네임 업데이트 쿼리문 edited_at 추가

functions/api/routes/auth/deleteUserPOST.js
- Firebase Auth에서 유저 탐색 실패 시 : 404 에러
- 삭제 실패, DB 관련 에러 시 : 500 에러
=> [FEAT] 회원 탈퇴 API 404 에러 추가

functions/api/routes/auth/deleteUserPOST.js
getAuth().deleteUser로도 Firebase Auth에 유저가 없으면 promise error를 받을 수 있어서 주석처리 한 getAuth() 지워도 될 것 같은데 어떤 것 같아?
=> [FEAT] try-catch문 분할

functions/api/routes/category/categoryPOST.js, functions/api/routes/content/contentPOST.js
카테고리, 콘텐츠 생성 API에서 중복 방지 로직을 삭제합니다.
=> 카테고리, 콘텐츠 생성 API 중복 방지 로직 삭제

functions/api/routes/content/contentPOST.js, functions/api/routes/user/userUpdateFcmTokenPUT.js
- closes #230 
description 도 혹시 모를 예외 상황을 방지하기 위해 전부 optional chaining 걸어뒀습니다!
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining
=> [FIX] og tag 스크래핑 시 image url property 가 없는 경우 처리

functions/api/routes/content/contentPOST.js
close #245 
- 콘텐츠 생성 API 내 크롤링 로직 삭제
=> [FIX] 콘텐츠 생성 API 크롤링 로직 삭제

.github/workflows/dev.yml, .github/workflows/prod.yml, functions/index.js
=> [FIX] Github Actions 오류 수정

.github/workflows/dev.yml, .github/workflows/prod.yml
- create-json 두 번 작동하도록 수정
- Github Actions를 통한 빌드 성공 시 Slack으로 메세지 전송하는 기능 추가
=> [FIX] Github Actions yml 파일 수정

.github/workflows/dev.yml, .github/workflows/prod.yml, firebase.json, functions/package.json
- Firebase Hosting 설정
- Build 성공 시 메세지 보내는 앱 수정
- deploy, dev 명령어 시 hosting도 같이 deploy 되도록 command 수정
=> [FEAT] Firebase Hosting과 Firebase Functions 연결

firebase.json
=> [FIX] Firebase Hosting에 region 명시

.firebaserc, functions/index.js
- .firebaserc 프로젝트 alias env 환경 이름과 같도록 수정
- NODE_ENV 판단하는 방법으로 project id 활용
=> [FIX] NODE_ENV 설정 오류 수정

functions/api/routes/health/healthCheckGET.js, functions/api/routes/health/index.js, functions/api/routes/index.js, functions/constants/responseMessage.js
close #300 
간단한 API라 바로 머지하겠습니다!
=> [FEAT] Upptime health check 연결

.github/workflows/dev.yml, .github/workflows/prod.yml, functions/api/routes/auth/signinPOST.js, functions/api/routes/auth/signupPOST.js, functions/api/routes/auth/userDELETE.js, functions/db/user.js
develop 릴리즈가 잘못 롤백되어 main 으로 새 1.0.3 버전 PR
=> [RELEASE] v1.0.3 

functions/api/routes/content/contentDELETE.js
해당 PR에서 작업한 내용을 한 줄로 요약해주세요.   
- close #313 
디테일한 작업 내역을 적어주세요.
주의할 사항이 있다면 적어주세요.
변경사항 (모듈 설치 등)이 있다면 적어주세요.
- 콘텐츠 삭제 시 알림이 삭제되지 않던 버그를 수정했습니다.
=> [FIX] 콘텐츠 삭제 시 알림도 삭제하도록 수정

README.md
- close #321 
변경 사항 없습니다 단지 dev push 서버 base url 이 변경되어서 한번 재배포 해주려고 올렸습니다
=> [FIX] dev push server url 변경에 따른 env 수정용 배포

functions/api/routes/community/communityPostGET.js, functions/constants/dummyImages.js, functions/constants/responseMessage.js, functions/constants/swagger/schemas/communitySchema.js, functions/db/community.js, functions/db/index.js
- close #336
- 커뮤니티 게시글 상세조회 API 구현
- user profile dummy image s3에 적재 후 주소 constants 로 추가해놨습니다.
- 실제 요청 결과
=> [FEAT] 커뮤니티 게시글 상세조회 API

functions/api/routes/auth/reissueTokenPOST.js, functions/api/routes/community/communityCategoriesGET.js, functions/constants/responseMessage.js, functions/db/community.js
close #341 
- response message 추가
- 쿼리 작성
- 엔드포인트 로직 구현
- 추가적으로, 잘못된 `/auth/reissue` 엔드포인트를 `/auth/token`으로 변경
=> [FEAT] 커뮤니티 카테고리 전체 조회 API

functions/api/routes/community/communityPostDELETE.js, functions/api/routes/community/index.js, functions/constants/responseMessage.js, functions/constants/swagger/schemas/communitySchema.js, functions/db/community.js, functions/middlewares/validator/communityValidator.js
- closed #355 
- 커뮤니티 게시글 삭제 API 구현
=> [FEAT] 커뮤니티 게시물 삭제 API
